# .gitleaks.toml
[extend]
# Patterns de fichiers à ignorer
paths = [
    '''data/.*''',
    '''.*\.db$''',
    '''.*\.db-wal$''',
    '''.*\.db-shm$''',
    '''.*\.sqlite.*$''',
    '''\.env$''',           # Exclut .env
    '''\.env\..*$''',       # Exclut .env.local, .env.prod, etc.
]


# Règles personnalisées restrictives
[[rules]]
id = "password-detection"
description = "Detect passwords"
regex = '''(?i)password\s*[:=]\s*["']([^"']{3,})["']'''

[[rules]]
id = "secret-detection"  
description = "Detect secrets and keys"
regex = '''(?i)(secret|private|key|token|api_key)\s*[:=]\s*["']([^"']{6,})["']'''

[[rules]]
id = "private-key-detection"
description = "Detect private keys"
regex = '''-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----'''

# NOUVELLE RÈGLE pour les variables d'environnement
[[rules]]
id = "env-private-keys"
description = "Detect environment private keys"
regex = '''(?i)[A-Z_]*PRIVATE[A-Z_]*\s*[:=]\s*["']([^"']{8,})["']'''

# RÈGLE SPÉCIFIQUE pour Solana (avec ET sans guillemets)
[[rules]]
id = "solana-keys"
description = "Detect Solana keys"
regex = '''(?i)SOLANA[A-Z_]*KEY\s*[:=]\s*["']?([^"'\s]{8,})["']?'''

# RÈGLE GÉNÉRALE pour variables d'environnement (avec ET sans guillemets)
[[rules]]
id = "sensitive-env-vars"
description = "Detect sensitive environment variables"
regex = '''(?i)(API_KEY|SECRET_KEY|PRIVATE_KEY|ACCESS_TOKEN|AUTH_TOKEN)\s*[:=]\s*["']?([^"'\s]{8,})["']?'''