# .gitleaks.toml
[extend]
# Patterns de fichiers à ignorer
paths = [
    '''data/.*''',
    '''.*\.db$''',
    '''.*\.db-wal$''',
    '''.*\.db-shm$''',
    '''.*\.sqlite.*$''',
    '''\.env$''',           # Exclut .env
    '''\.env\..*$''',       # Exclut .env.local, .env.prod, etc.
    "data/",
    "**/*.db",
    "**/*.db-wal", 
    "**/*.db-shm",
    "**/*.sqlite*",
    ".env",              # Format simple
    ".env.*",            # Format simple pour .env.local, etc.
     '''data/.*''',
    '''.*\.db.*$''',
    '''.*\.sqlite.*$''',
    '''^\.env$''',        # ^ = début de ligne, $ = fin de ligne
    '''^\.env\..*$''',    # Pour .env.local, .env.prod, etc.
    '''__pycache__/.*''',
    '''.*\.pyc$''',
    '''.*\.pyo$''',
    '''.*\.pyd$''',
    '''.pytest_cache/.*''',
    '''\.mypy_cache/.*''',
    "__pycache__/",
    "**/__pycache__/**",
    "**/*.pyc",
    "**/*.pyo", 
    "**/*.pyd",
    ".pytest_cache/",
    ".mypy_cache/",
"venv/",
"env/", 
"mon_env/",
".venv/",
"**/venv/**",
"**/env/**",
"**/mon_env/**",
"**/.venv/**",
]


[allowlist]
# Regex qui excluent dossiers et fichiers lourds
paths = [
    '''(?i)\.git[\\/]''',
    '''(?i)\.venv[\\/]''',
    '''(?i)venv[\\/]''',
    '''(?i)env[\\/]''',
    '''(?i)mon_env[\\/]''',
    '''(?i)__pycache__[\\/]''',
    '''(?i)\.pytest_cache[\\/]''',
    '''(?i)\.mypy_cache[\\/]''',
    '''(?i)data[\\/]''',
    '''(?i).*\.db$''',
    '''(?i).*\.db-wal$''',
    '''(?i).*\.db-shm$''',
    '''(?i).*\.sqlite.*$''',
    '''(?i)\.env(\..*)?$''',
    '''(?i).*\.pyc$''',
    '''(?i).*\.pyo$''',
    '''(?i).*\.pyd$''',
]

# Règles personnalisées restrictives
[[rules]]
id = "password-detection"
description = "Detect passwords"
regex = '''(?i)password\s*[:=]\s*["']([^"']{3,})["']'''
[rules.allowlist]
paths = [
    '''(?i)\.env(\..*)?$''',
    '''(?i)mon_env[\\/]''',
]
regexes = [
    '''(?i).*your.*''',
    '''(?i).*example.*''',
    '''(?i).*getenv.*''',
    '''(?i).*\.get\(.*''',
    '''os\.getenv\(''',
    '''getenv\(''',
    '''env\.get\(''',
    '''process\.env\.''',
    '''config\.get\(''',
    '''settings\.''',
    '''environ\.get\(''',
]

[[rules]]
id = "secret-detection"  
description = "Detect secrets and keys"
regex = '''(?i)(secret|private|token|api_key)\s*[:=]\s*["']([^"']{6,})["']'''
[rules.allowlist]
paths = [
    '''(?i)\.env(\..*)?$''',
    '''(?i)mon_env[\\/]''',
]
regexes = [
    '''(?i).*your.*''',
    '''(?i).*example.*''',
    '''(?i).*getenv.*''',
    '''(?i).*\.get\(.*''',
    '''os\.getenv\(''',
    '''getenv\(''',
    '''env\.get\(''',
    '''process\.env\.''',
    '''config\.get\(''',
    '''settings\.''',
    '''environ\.get\(''',
    '''.*tokenSymbol.*''',
]

[[rules]]
id = "private-key-detection"
description = "Detect private keys"
regex = '''-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----'''
[rules.allowlist]
paths = [
    '''(?i)\.env(\..*)?$''',
    '''(?i)mon_env[\\/]''',
]
regexes = [
    '''(?i).*your.*''',
    '''(?i).*example.*''',
    '''(?i).*getenv.*''',
    '''(?i).*\.get\(.*''',
    '''os\.getenv\(''',
    '''getenv\(''',
    '''env\.get\(''',
    '''process\.env\.''',
    '''config\.get\(''',
    '''settings\.''',
    '''environ\.get\(''',
]

# NOUVELLE RÈGLE pour les variables d'environnement
[[rules]]
id = "env-private-keys"
description = "Detect environment private keys"
regex = '''(?i)[A-Z_]*PRIVATE[A-Z_]*\s*[:=]\s*["']([^"']{8,})["']'''
[rules.allowlist]
paths = [
    '''(?i)\.env(\..*)?$''',
    '''(?i)mon_env[\\/]''',
]
regexes = [
    '''(?i).*your.*''',
    '''(?i).*example.*''',
    '''(?i).*getenv.*''',
    '''(?i).*\.get\(.*''',
    '''os\.getenv\(''',
    '''getenv\(''',
    '''env\.get\(''',
    '''process\.env\.''',
    '''config\.get\(''',
    '''settings\.''',
    '''environ\.get\(''',
]

# RÈGLE SPÉCIFIQUE pour Solana (avec ET sans guillemets)
[[rules]]
id = "solana-keys"
description = "Detect Solana keys"
regex = '''(?i)SOLANA[A-Z_]*KEY\s*[:=]\s*["']?([^"'\s]{8,})["']?'''
[rules.allowlist]
paths = [
    '''(?i)\.env(\..*)?$''',
    '''(?i)mon_env[\\/]''',
]
regexes = [
    '''(?i).*your.*''',
    '''(?i).*example.*''',
    '''(?i).*getenv.*''',
    '''(?i).*\.get\(.*''',
    '''os\.getenv\(''',
    '''getenv\(''',
    '''env\.get\(''',
    '''process\.env\.''',
    '''config\.get\(''',
    '''settings\.''',
    '''environ\.get\(''',
]

# RÈGLE GÉNÉRALE pour variables d'environnement (avec ET sans guillemets)
[[rules]]
id = "sensitive-env-vars"
description = "Detect sensitive environment variables"
regex = '''(?i)^[^#]*(?:export\s+)?([A-Z_]*(?:KEY|SECRET|PASSWORD)[A-Z_]*)\s*[:=]\s*["']?([^"'\s()]{8,})["']?\s*(?:#.*)?$'''
[rules.allowlist]
paths = [
    '''(?i)\.env(\..*)?$''',
    '''(?i)mon_env[\\/]''',
]
