# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks
        language: system
        args: ['detect', '--source', '.','--config','.gitleaks.toml','--verbose','no-git']
        pass_filenames: false