CREATE TABLE tokens (
    address TEXT PRIMARY KEY,
    symbol TEXT,
    name TEXT,
    decimals INTEGER DEFAULT 9,
    price_usd REAL DEFAULT 0.0,
    logo_uri TEXT,
    coingecko_id TEXT,
    is_verified BOOLEAN DEFAULT 0,
    timestamp_token_created INTEGER DEFAULT 0,
    market_cap REAL DEFAULT 0.0,
    volume_5m REAL DEFAULT 0.0,
    volume_1h REAL DEFAULT 0.0,
    volume_6h REAL DEFAULT 0.0,
    volume_24h REAL DEFAULT 0.0,
    price_change_5m REAL DEFAULT 0.0,
    price_change_1h REAL DEFAULT 0.0,
    price_change_6h REAL DEFAULT 0.0,
    price_change_24h REAL DEFAULT 0.0,
    creator_address TEXT,
    bonding_curve_progress REAL DEFAULT 0.0,
    holder_count INTEGER DEFAULT 0,
    last_price_update INTEGER DEFAULT 0,
    metadata_source TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
