CREATE TABLE transactions (
    id INTEGER PRIMARY KEY,
    signature TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    slot INTEGER,
    block_time INTEGER,
    amount REAL DEFAULT 0.0,
    token_mint TEXT,
    token_symbol TEXT,
    token_name TEXT,
    transaction_type TEXT,
    token_amount REAL DEFAULT 0.0,
    price_per_token REAL DEFAULT 0.0,
    fee REAL DEFAULT 0.0,
    status TEXT DEFAULT 'success',
    is_token_transaction BOOLEAN DEFAULT 0,
    is_large_token_amount BOOLEAN DEFAULT 0,
    detection_delay REAL DEFAULT 0.0,
    wallet_priority_at_detection REAL DEFAULT 1.0,
    scan_cycle_id TEXT,
    source TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
